# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 9) do

  create_table "blog_posts", :force => true do |t|
    t.column "title",          :string,   :limit => 100, :default => "", :null => false
    t.column "content",        :text
    t.column "author_id",      :integer
    t.column "status",         :string,   :limit => 20,  :default => "", :null => false
    t.column "created_at",     :datetime
    t.column "updated_at",     :datetime
    t.column "comments_count", :integer,  :limit => 4,   :default => 0,  :null => false
  end

  add_index "blog_posts", ["author_id"], :name => "index_blog_posts_on_author_id"

  create_table "categories", :force => true do |t|
    t.column "name",        :string, :limit => 50, :default => "", :null => false
    t.column "short_name",  :string, :limit => 30, :default => "", :null => false
    t.column "description", :string,               :default => "", :null => false
  end

  create_table "categories_posts", :force => true do |t|
    t.column "category_id", :integer, :null => false
    t.column "post_id",     :integer, :null => false
  end

  add_index "categories_posts", ["category_id"], :name => "index_categories_posts_on_category_id"
  add_index "categories_posts", ["post_id"], :name => "index_categories_posts_on_post_id"

  create_table "comments", :force => true do |t|
    t.column "post_id",      :integer,                :default => 0,  :null => false
    t.column "author",       :string,   :limit => 25, :default => "", :null => false
    t.column "author_email", :string,   :limit => 50, :default => "", :null => false
    t.column "content",      :text,                   :default => "", :null => false
    t.column "status",       :string,   :limit => 25, :default => "", :null => false
    t.column "created_at",   :datetime
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "users", :force => true do |t|
    t.column "username",        :string,  :limit => 25, :default => "", :null => false
    t.column "hashed_password", :string,  :limit => 40, :default => "", :null => false
    t.column "first_name",      :string,  :limit => 25, :default => "", :null => false
    t.column "last_name",       :string,  :limit => 40, :default => "", :null => false
    t.column "email",           :string,  :limit => 50, :default => "", :null => false
    t.column "display_name",    :string,  :limit => 25, :default => "", :null => false
    t.column "user_level",      :integer, :limit => 3,  :default => 0,  :null => false
    t.column "salt",            :string,  :limit => 40
  end

end
